# Step 1: Build the Go application
FROM golang:1.23.4 AS builder

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go modules and download dependencies
COPY ./classe-project/project-04/go.mod  ./
RUN go mod download

# Copy the source code into the container
COPY ./classe-project/project-04 .

# Build the Go application
RUN go build -o api .

# Step 2: Create the final image
FROM alpine:latest

# Install any required dependencies
RUN apk --no-cache add ca-certificates

# Set the working directory in the container
WORKDIR /root/

# Copy the built Go application from the builder stage
COPY --from=builder /app/api .

# Expose the port your application listens on
EXPOSE 8080

# Command to run the Go application
CMD ["/app/api"]
